# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cats + Pizza ^ Coffe + Robots
email: arangel.glz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The Opinions Expressed In This Blog Are My Own And Not Necessarily Those Of My Employer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "rangelalejandro.com" # the base hostname & protocol for your site
twitter_username: arangel_glz
github_username:  alejandrorangel

# Build settings
markdown: kramdown
